

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./h2/test
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update